### ISSUE TITLE
Fazer download das base em script

### ISSUE THREAD

**Issue by garcia-pedro-hr** [brunomcr/1MLET_FASE1_TECH_CHALLENGE#3]

**Comment by brunomcr** [comment]
Feita otimizacao no comando para limpar o terminal.

**Comment by rodrigosantili** [comment]
Realizei a troca do método de download dos arquivos. 
Como estávamos com dificuldades de inserir os dados no database, agora estamos trazendo os arquivos em .json utilizando a metodologia de webscraping.

@brunomcr e @garcia-pedro-hr . Favor reavaliarem as alterações e aprovar a branch.

**Comment by rodrigosantili** [comment]
@brunomcr e @garcia-pedro-hr . Favor reavaliarem as alterações e aprovar a branch.
