### ISSUE TITLE
Criação do Docker File

### ISSUE THREAD

**Issue by garcia-pedro-hr** [brunomcr/1MLET_FASE1_TECH_CHALLENGE#4]

**Comment by brunomcr** [comment]
Criei um primeiro dockerfile, para a imagem da API. 

- Python 3.12 slim ( precisaria ver se vamos usar outra versao disponivel no dockerHub)
- Instalação dos requisitos, incluir FastAPI e Uvicorn para subir a aplicacao. 

Estou rodando a imagem no conteiner com o comando do Uvicorn, acredito que possa exisitir outro meio mais dentro das boas praticas. 



Aproveitei e inclui algumas informacoes de como rodar o docker, no README.md

**Comment by brunomcr** [comment]
Acreito que precisamos fazer a configuracao de network, bridge ou a utilizacao de host.

**Comment by danielaschutt** [comment]
Beleza, deixa eu fazer essa parte porque tu ta assinado em basicamente todos os cards uhdauhdsa

**Comment by brunomcr** [comment]
Foi mal. 


Criei um issue de Docker Compose tbm. pois vamos precisar para criar a aplicacao dos container de banco, api e nao sei se vai precisar de mais.

**Comment by danielaschutt** [comment]
Beleza, posso tocar o docker compose também. Valeu!

**Comment by brunomcr** [comment]
Feita a remoção da linha onde expoem a porta da aplicação. 

A referencia das portas ja esta sendo feita no docker-compose.
