### ISSUE TITLE
Desenho da Arquitetura da API 

### ISSUE THREAD

**Issue by garcia-pedro-hr** [brunomcr/1MLET_FASE1_TECH_CHALLENGE#5]
- adicionar plano de ingestão e alimentação dos dados para modelo de ML

**Comment by brunomcr** [comment]
@garcia-pedro-hr pensei em fazer em drawio pois conseguimos integrar direito no repositorio do github. 

é uma ideia.

**Comment by brunomcr** [comment]
Inclui uma nova visao para UML, incorpoarando toda a visao do projeto, scrap, load, request de authenticacao, request de dados e request de ML
