### ISSUE TITLE
Setup Inicial do Projeto

### ISSUE THREAD

**Issue by garcia-pedro-hr** [brunomcr/1MLET_FASE1_TECH_CHALLENGE#6]
Criar um serviço minimamente funcional com FastAPI
- Serviço deve subir apropriadamente

#4

**Comment by brunomcr** [comment]
Criei uma branch nova para  o SetUp da API, fiz um script simples somente fazendo um HELLO.


Precisa das libs:
- fastapi
- uvicorn

Para inciar o app, utilizar o comando:  `uvicorn api_server:app --reload`
