### ISSUE TITLE
Definição dos Endpoints

### ISSUE THREAD

**Issue by garcia-pedro-hr** [brunomcr/1MLET_FASE1_TECH_CHALLENGE#8]
- GET /production
- GET /processing
- GET /sales
- GET /import
- GET /export]

DEPENDS ON #6

**Comment by rodrigosantili** [comment]
Iniciei o desenvolvimento da feature dos endpoints. O mesmo esta na branch "feat_dev_endpoints".
Iniciei a busca dos dados pelos arquivos, pois entendo que ainda não temos os dados no database. 
Assim que o mongodb e os dados estiveremprontos mudamos a função de json para o banco.
